-- Create admin user for Acme Corporation
-- Email: admin@acme-corp.com
-- Password: TestPass123!
-- Organization: Acme Corporation (00000000-0000-0000-0000-000000000001)
-- Role: Admin

-- Step 1: Create auth user
-- Note: This uses Supabase's auth.users table and requires service role access
-- The user_id will be generated by Supabase auth system

DO $$
DECLARE
  new_user_id UUID;
BEGIN
  -- Create the auth user using Supabase's admin API would be preferred
  -- For direct SQL insertion (service role only):

  -- Generate a new UUID for the user
  new_user_id := gen_random_uuid();

  -- Insert into auth.users (requires service role privileges)
  INSERT INTO auth.users (
    id,
    instance_id,
    email,
    encrypted_password,
    email_confirmed_at,
    created_at,
    updated_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    role,
    aud,
    confirmation_token,
    email_change_token_current,
    email_change_token_new
  ) VALUES (
    new_user_id,
    '00000000-0000-0000-0000-000000000000', -- default instance_id
    'admin@acme-corp.com',
    crypt('TestPass123!', gen_salt('bf')), -- bcrypt hash
    now(), -- email confirmed immediately
    now(),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"full_name":"Admin User"}'::jsonb,
    false,
    'authenticated',
    'authenticated',
    '',
    '',
    ''
  ) ON CONFLICT (email) DO NOTHING
  RETURNING id INTO new_user_id;

  -- If user already exists, get their ID
  IF new_user_id IS NULL THEN
    SELECT id INTO new_user_id FROM auth.users WHERE email = 'admin@acme-corp.com';
  END IF;

  -- Step 2: Create/update user profile
  INSERT INTO public.user_profiles (
    id,
    full_name,
    avatar_url,
    created_at,
    updated_at
  ) VALUES (
    new_user_id,
    'Admin User',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=AdminUser',
    now(),
    now()
  ) ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now();

  -- Step 3: Add to Acme Corporation with admin role
  INSERT INTO public.organization_members (
    organization_id,
    user_id,
    role,
    is_active,
    joined_at,
    created_at,
    updated_at
  ) VALUES (
    '00000000-0000-0000-0000-000000000001', -- Acme Corporation
    new_user_id,
    'admin',
    true,
    now(),
    now(),
    now()
  ) ON CONFLICT (organization_id, user_id) DO UPDATE SET
    role = EXCLUDED.role,
    is_active = EXCLUDED.is_active,
    updated_at = now();

  -- Output the result
  RAISE NOTICE 'User created successfully with ID: %', new_user_id;

END $$;

-- Verification query
SELECT
  u.id as user_id,
  u.email,
  u.created_at as auth_created_at,
  up.full_name,
  om.organization_id,
  o.name as organization_name,
  om.role
FROM auth.users u
LEFT JOIN public.user_profiles up ON u.id = up.id
LEFT JOIN public.organization_members om ON u.id = om.user_id
LEFT JOIN public.organizations o ON om.organization_id = o.id
WHERE u.email = 'admin@acme-corp.com';
